### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for \create-flatfile-vuejs\server\index.ts

### ISSUE THREAD

**Issue by jakenuts** [FlatFilers/create-flatfile-vuejs#8]
I was hoping to find a simple example of a vue csv import using FlatFile.  After cloning the repo and installing the packages with pnpm, when I run 'dev' I get this: 

`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for \create-flatfile-vuejs\server\index.ts`

![image](https://github.com/FlatFilers/create-flatfile-vuejs/assets/344606/4e37b0bc-cbfe-4d13-b93b-60398e792944)

**Comment by jakenuts** [comment]
As a side note, as the whole space/workbook/listener thing is already a bit of a mystery to me (granted I've read nothing, one of those) the existence of two identical files in the workbook folder isn't helpful. That neither appears to be used anywhere is either great news (I don't have to learn that concept) or terrible news (this is an incomplete demo). Hoping it's the former.

**Comment by Arsik36** [comment]
Hey Jake, thank you for reaching out to us. Are you using it to launch a new space each time, or to reuse an existing space

**Comment by Arsik36** [comment]
I am testing and getting CORS errors that I just ticketed, but I am not sure yet how to reproduce what you are seeing. Can you provide me with steps to reproduce?

**Comment by jakenuts** [comment]
Sorry, was a bit grumpy last night. I suspect it has to do with my version of Node. Was on 20 something, now on v21.6.1. Worked through some of the suggested fixes but finally resolved it by changing the backend launch to this: 

`"dev:backend": "node --loader ts-node/esm ./server/index.ts",`

**Comment by gammons** [comment]
I can repro this issue as well.

**Comment by gammons** [comment]
side note, it would be great if the README could show how to actually run this demo.  which one do I run?  `npm run dev`?  `npm start`?  Is there a difference?

**Comment by Arsik36** [comment]
Thank you, this is a very good feedback. I will PR our README to make it clearer. I personally use `npm run dev` with Vue JS
